SERPAPI_API_KEY = "d355f1960e0f556f58f6f1d86e8253920cc38f2558cc3d7d0189ad65a775d684"
OPENAI_API_KEY = "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"
